global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: hw_proxy
    static_configs:
      - targets: ["${MGMT_IP}:9002"]
        labels:
          service: hw_proxy
          stack: odoo_prod
    metrics_path: /hw_proxy/metrics
